// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: auth.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers_RuntimeSupport.h>
#else
 #import "GPBProtocolBuffers_RuntimeSupport.h"
#endif

 #import "Auth.pbobjc.h"
// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

#pragma mark - AuthRoot

@implementation AuthRoot

// No extensions in the file and no imports, so no need to generate
// +extensionRegistry.

@end

#pragma mark - AuthRoot_FileDescriptor

static GPBFileDescriptor *AuthRoot_FileDescriptor(void) {
  // This is called by +initialize so there is no need to worry
  // about thread safety of the singleton.
  static GPBFileDescriptor *descriptor = NULL;
  if (!descriptor) {
    GPB_DEBUG_CHECK_RUNTIME_VERSIONS();
    descriptor = [[GPBFileDescriptor alloc] initWithPackage:@"protocol.protobuf"
                                                     syntax:GPBFileSyntaxProto3];
  }
  return descriptor;
}

#pragma mark - AuthRequest

@implementation AuthRequest

@dynamic uid;
@dynamic domain;
@dynamic token;
@dynamic clientType;
@dynamic guid;
@dynamic appId;
@dynamic timestamp;

typedef struct AuthRequest__storage_ {
  uint32_t _has_storage_[1];
  int32_t domain;
  int32_t clientType;
  NSString *uid;
  NSString *token;
  NSString *guid;
  NSString *appId;
  int64_t timestamp;
} AuthRequest__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "uid",
        .dataTypeSpecific.className = NULL,
        .number = AuthRequest_FieldNumber_Uid,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(AuthRequest__storage_, uid),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "domain",
        .dataTypeSpecific.className = NULL,
        .number = AuthRequest_FieldNumber_Domain,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(AuthRequest__storage_, domain),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeInt32,
      },
      {
        .name = "token",
        .dataTypeSpecific.className = NULL,
        .number = AuthRequest_FieldNumber_Token,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(AuthRequest__storage_, token),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "clientType",
        .dataTypeSpecific.className = NULL,
        .number = AuthRequest_FieldNumber_ClientType,
        .hasIndex = 3,
        .offset = (uint32_t)offsetof(AuthRequest__storage_, clientType),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeInt32,
      },
      {
        .name = "guid",
        .dataTypeSpecific.className = NULL,
        .number = AuthRequest_FieldNumber_Guid,
        .hasIndex = 4,
        .offset = (uint32_t)offsetof(AuthRequest__storage_, guid),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "appId",
        .dataTypeSpecific.className = NULL,
        .number = AuthRequest_FieldNumber_AppId,
        .hasIndex = 5,
        .offset = (uint32_t)offsetof(AuthRequest__storage_, appId),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "timestamp",
        .dataTypeSpecific.className = NULL,
        .number = AuthRequest_FieldNumber_Timestamp,
        .hasIndex = 6,
        .offset = (uint32_t)offsetof(AuthRequest__storage_, timestamp),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeInt64,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[AuthRequest class]
                                     rootClass:[AuthRoot class]
                                          file:AuthRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(AuthRequest__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
#if !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    static const char *extraTextFormatInfo =
        "\002\004\n\000\006\005\000";
    [localDescriptor setupExtraTextInfo:extraTextFormatInfo];
#endif  // !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - AuthResponse

@implementation AuthResponse

@dynamic status;
@dynamic code;
@dynamic msg;

typedef struct AuthResponse__storage_ {
  uint32_t _has_storage_[1];
  int32_t status;
  int32_t code;
  NSString *msg;
} AuthResponse__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "status",
        .dataTypeSpecific.className = NULL,
        .number = AuthResponse_FieldNumber_Status,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(AuthResponse__storage_, status),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeInt32,
      },
      {
        .name = "code",
        .dataTypeSpecific.className = NULL,
        .number = AuthResponse_FieldNumber_Code,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(AuthResponse__storage_, code),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeInt32,
      },
      {
        .name = "msg",
        .dataTypeSpecific.className = NULL,
        .number = AuthResponse_FieldNumber_Msg,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(AuthResponse__storage_, msg),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[AuthResponse class]
                                     rootClass:[AuthRoot class]
                                          file:AuthRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(AuthResponse__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - Enum AuthResponse_Status

GPBEnumDescriptor *AuthResponse_Status_EnumDescriptor(void) {
  static GPBEnumDescriptor *descriptor = NULL;
  if (!descriptor) {
    static const char *valueNames =
        "Ok\000Err\000";
    static const int32_t values[] = {
        AuthResponse_Status_Ok,
        AuthResponse_Status_Err,
    };
    GPBEnumDescriptor *worker =
        [GPBEnumDescriptor allocDescriptorForName:GPBNSStringifySymbol(AuthResponse_Status)
                                       valueNames:valueNames
                                           values:values
                                            count:(uint32_t)(sizeof(values) / sizeof(int32_t))
                                     enumVerifier:AuthResponse_Status_IsValidValue];
    if (!OSAtomicCompareAndSwapPtrBarrier(nil, worker, (void * volatile *)&descriptor)) {
      [worker release];
    }
  }
  return descriptor;
}

BOOL AuthResponse_Status_IsValidValue(int32_t value__) {
  switch (value__) {
    case AuthResponse_Status_Ok:
    case AuthResponse_Status_Err:
      return YES;
    default:
      return NO;
  }
}


#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
