// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: auth.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

NS_ASSUME_NONNULL_BEGIN

#pragma mark - Enum AuthResponse_Status

/** 状态枚举 */
typedef GPB_ENUM(AuthResponse_Status) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  AuthResponse_Status_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  AuthResponse_Status_Ok = 0,
  AuthResponse_Status_Err = -1,
};

GPBEnumDescriptor *AuthResponse_Status_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL AuthResponse_Status_IsValidValue(int32_t value);

#pragma mark - AuthRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface AuthRoot : GPBRootObject
@end

#pragma mark - AuthRequest

typedef GPB_ENUM(AuthRequest_FieldNumber) {
  AuthRequest_FieldNumber_Uid = 1,
  AuthRequest_FieldNumber_Domain = 2,
  AuthRequest_FieldNumber_Token = 3,
  AuthRequest_FieldNumber_ClientType = 4,
  AuthRequest_FieldNumber_Guid = 5,
  AuthRequest_FieldNumber_AppId = 6,
  AuthRequest_FieldNumber_Timestamp = 7,
};

@interface AuthRequest : GPBMessage

/** 用户id */
@property(nonatomic, readwrite, copy, null_resettable) NSString *uid;

/** 用户所属类别，0-员工（呱呱） */
@property(nonatomic, readwrite) int32_t domain;

/** 用户token */
@property(nonatomic, readwrite, copy, null_resettable) NSString *token;

/** IOS/Android/Web/Wap */
@property(nonatomic, readwrite) int32_t clientType;

/** app重新安装会变，web端怎么变？ */
@property(nonatomic, readwrite, copy, null_resettable) NSString *guid;

/** 标识哪个应用 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *appId;

/** 发包时间戳 */
@property(nonatomic, readwrite) int64_t timestamp;

@end

#pragma mark - AuthResponse

typedef GPB_ENUM(AuthResponse_FieldNumber) {
  AuthResponse_FieldNumber_Status = 1,
  AuthResponse_FieldNumber_Code = 2,
  AuthResponse_FieldNumber_Msg = 3,
};

@interface AuthResponse : GPBMessage

/** 状态，使用枚举 */
@property(nonatomic, readwrite) int32_t status;

/** 状态码，统一定义的错误码 */
@property(nonatomic, readwrite) int32_t code;

/** 状态描述 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *msg;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
