// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: c2ai.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

NS_ASSUME_NONNULL_BEGIN

#pragma mark - C2AiRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface C2AiRoot : GPBRootObject
@end

#pragma mark - C2AiRequest

typedef GPB_ENUM(C2AiRequest_FieldNumber) {
  C2AiRequest_FieldNumber_From = 1,
  C2AiRequest_FieldNumber_FromName = 2,
  C2AiRequest_FieldNumber_FromDomain = 3,
  C2AiRequest_FieldNumber_Guid = 4,
  C2AiRequest_FieldNumber_ChatId = 5,
  C2AiRequest_FieldNumber_SceneId = 6,
  C2AiRequest_FieldNumber_Content = 7,
  C2AiRequest_FieldNumber_Type = 8,
  C2AiRequest_FieldNumber_AppId = 9,
  C2AiRequest_FieldNumber_Ext = 10,
};

/**
 * 用户发给机器人的消息
 **/
@interface C2AiRequest : GPBMessage

/** 发送者ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *from;

@property(nonatomic, readwrite, copy, null_resettable) NSString *fromName;

/** 发送者所属用户类型,具体见DomainType */
@property(nonatomic, readwrite) int32_t fromDomain;

/** 用户guid */
@property(nonatomic, readwrite, copy, null_resettable) NSString *guid;

/** 会话ID */
@property(nonatomic, readwrite) int64_t chatId;

/** 场景ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *sceneId;

/** 消息内容 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *content;

/** 消息类型，比如文本，图片，文件等 */
@property(nonatomic, readwrite) int32_t type;

/** app标识，如瓜子，毛豆app */
@property(nonatomic, readwrite, copy, null_resettable) NSString *appId;

/** 扩展内容，建议采用富文本 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ext;

@end

#pragma mark - C2AiResponse

typedef GPB_ENUM(C2AiResponse_FieldNumber) {
  C2AiResponse_FieldNumber_Msgid = 1,
  C2AiResponse_FieldNumber_Timestamp = 2,
};

@interface C2AiResponse : GPBMessage

/** 落地存储的消息id（针对此条消息） */
@property(nonatomic, readwrite) int64_t msgid;

/** 收到群聊消息的时间戳 */
@property(nonatomic, readwrite) int64_t timestamp;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
