// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: c2gsend.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

NS_ASSUME_NONNULL_BEGIN

#pragma mark - C2GsendRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface C2GsendRoot : GPBRootObject
@end

#pragma mark - C2GSendRequest

typedef GPB_ENUM(C2GSendRequest_FieldNumber) {
  C2GSendRequest_FieldNumber_From = 1,
  C2GSendRequest_FieldNumber_FromName = 2,
  C2GSendRequest_FieldNumber_FromDomain = 3,
  C2GSendRequest_FieldNumber_ChatId = 4,
  C2GSendRequest_FieldNumber_Content = 5,
  C2GSendRequest_FieldNumber_Type = 6,
};

@interface C2GSendRequest : GPBMessage

/** 发送者 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *from;

@property(nonatomic, readwrite, copy, null_resettable) NSString *fromName;

@property(nonatomic, readwrite) int32_t fromDomain;

/** 目的群 */
@property(nonatomic, readwrite) int64_t chatId;

/** 消息内容 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *content;

/** 消息类型，比如文本，图片，文件等 */
@property(nonatomic, readwrite) int32_t type;

@end

#pragma mark - C2GSendResponse

typedef GPB_ENUM(C2GSendResponse_FieldNumber) {
  C2GSendResponse_FieldNumber_Msgid = 1,
  C2GSendResponse_FieldNumber_Timestamp = 2,
};

@interface C2GSendResponse : GPBMessage

/** 落地存储的消息id（针对此条消息） */
@property(nonatomic, readwrite) int64_t msgid;

/** 收到群聊消息的时间戳 */
@property(nonatomic, readwrite) int64_t timestamp;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
