// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: clienttype.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers_RuntimeSupport.h>
#else
 #import "GPBProtocolBuffers_RuntimeSupport.h"
#endif

 #import "Clienttype.pbobjc.h"
// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

#pragma mark - ClienttypeRoot

@implementation ClienttypeRoot

// No extensions in the file and no imports, so no need to generate
// +extensionRegistry.

@end

#pragma mark - Enum ClientType

GPBEnumDescriptor *ClientType_EnumDescriptor(void) {
  static GPBEnumDescriptor *descriptor = NULL;
  if (!descriptor) {
    static const char *valueNames =
        "ClientTypeApp\000ClientTypeWeb\000ClientTypeAn"
        "droid\000ClientTypeIos\000ClientTypeWap\000Client"
        "TypeThird\000ClientTypeAll\000ClientTypeWebwap"
        "\000";
    static const int32_t values[] = {
        ClientType_ClientTypeApp,
        ClientType_ClientTypeWeb,
        ClientType_ClientTypeAndroid,
        ClientType_ClientTypeIos,
        ClientType_ClientTypeWap,
        ClientType_ClientTypeThird,
        ClientType_ClientTypeAll,
        ClientType_ClientTypeWebwap,
    };
    GPBEnumDescriptor *worker =
        [GPBEnumDescriptor allocDescriptorForName:GPBNSStringifySymbol(ClientType)
                                       valueNames:valueNames
                                           values:values
                                            count:(uint32_t)(sizeof(values) / sizeof(int32_t))
                                     enumVerifier:ClientType_IsValidValue];
    if (!OSAtomicCompareAndSwapPtrBarrier(nil, worker, (void * volatile *)&descriptor)) {
      [worker release];
    }
  }
  return descriptor;
}

BOOL ClientType_IsValidValue(int32_t value__) {
  switch (value__) {
    case ClientType_ClientTypeApp:
    case ClientType_ClientTypeWeb:
    case ClientType_ClientTypeAndroid:
    case ClientType_ClientTypeIos:
    case ClientType_ClientTypeWap:
    case ClientType_ClientTypeThird:
    case ClientType_ClientTypeAll:
    case ClientType_ClientTypeWebwap:
      return YES;
    default:
      return NO;
  }
}


#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
