// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: domaintype.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers_RuntimeSupport.h>
#else
 #import "GPBProtocolBuffers_RuntimeSupport.h"
#endif

 #import "Domaintype.pbobjc.h"
// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

#pragma mark - DomaintypeRoot

@implementation DomaintypeRoot

// No extensions in the file and no imports, so no need to generate
// +extensionRegistry.

@end

#pragma mark - Enum DomainType

GPBEnumDescriptor *DomainType_EnumDescriptor(void) {
  static GPBEnumDescriptor *descriptor = NULL;
  if (!descriptor) {
    static const char *valueNames =
        "DomainTypeStaff\000DomainTypeGroup\000DomainTy"
        "peWorkspace\000DomainTypeOffacc\000DomainTypeC"
        "ustomService\000DomainTypeAnonymous\000DomainT"
        "ypeRobot\000DomainTypeExternal\000";
    static const int32_t values[] = {
        DomainType_DomainTypeStaff,
        DomainType_DomainTypeGroup,
        DomainType_DomainTypeWorkspace,
        DomainType_DomainTypeOffacc,
        DomainType_DomainTypeCustomService,
        DomainType_DomainTypeAnonymous,
        DomainType_DomainTypeRobot,
        DomainType_DomainTypeExternal,
    };
    GPBEnumDescriptor *worker =
        [GPBEnumDescriptor allocDescriptorForName:GPBNSStringifySymbol(DomainType)
                                       valueNames:valueNames
                                           values:values
                                            count:(uint32_t)(sizeof(values) / sizeof(int32_t))
                                     enumVerifier:DomainType_IsValidValue];
    if (!OSAtomicCompareAndSwapPtrBarrier(nil, worker, (void * volatile *)&descriptor)) {
      [worker release];
    }
  }
  return descriptor;
}

BOOL DomainType_IsValidValue(int32_t value__) {
  switch (value__) {
    case DomainType_DomainTypeStaff:
    case DomainType_DomainTypeGroup:
    case DomainType_DomainTypeWorkspace:
    case DomainType_DomainTypeOffacc:
    case DomainType_DomainTypeCustomService:
    case DomainType_DomainTypeAnonymous:
    case DomainType_DomainTypeRobot:
    case DomainType_DomainTypeExternal:
      return YES;
    default:
      return NO;
  }
}


#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
