// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messagecmd.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

NS_ASSUME_NONNULL_BEGIN

#pragma mark - Enum CmdID

typedef GPB_ENUM(CmdID) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  CmdID_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  /** 未使用的命令号，proto3要求枚举第一个元素从0开始，用于默认的消息处理Handler */
  CmdID_CmdIdDefault = 0,

  /** 登录 */
  CmdID_CmdIdAuth = 1001,

  /** 登出 */
  CmdID_CmdIdLogout = 1002,

  /** 踢人 */
  CmdID_CmdIdKickout = 1003,

  /** 心跳 */
  CmdID_CmdIdKeepalive = 6,

  /** client to group */
  CmdID_CmdIdC2Gsend = 1008,

  /** client to group */
  CmdID_CmdIdC2Gpush = 1009,

  /** 消息通知 */
  CmdID_CmdIdNotify = 3000,

  /** 消息同步 */
  CmdID_CmdIdSync = 3001,

  /** 用户发给客服的消息 */
  CmdID_CmdIdC2Kf = 3002,

  /** 客服发给用户的消息 */
  CmdID_CmdIdKf2C = 3003,

  /** 用户发给机器人的消息 */
  CmdID_CmdIdC2Ai = 3004,

  /** 机器人发给用户的消息 */
  CmdID_CmdIdAi2C = 3005,

  /** 请求分配客服 */
  CmdID_CmdIdDistributeSend = 3006,

  /** 返回分配的客服 */
  CmdID_CmdIdDistributePush = 3007,

  /** 场景结束 */
  CmdID_CmdIdSceneEndSend = 3008,

  /** 场景结束 */
  CmdID_CmdIdSceneEndPush = 3009,

  /** 客服邀请用户评价的消息 */
  CmdID_CmdIdRate = 3010,

  /** 客服邀请用户评价的消息 */
  CmdID_CmdIdHistory = 3011,

  /** 欢迎语 */
  CmdID_CmdIdWelcome = 3012,

  /** 系统消息 */
  CmdID_CmdIdSystemMsg = 3013,
};

GPBEnumDescriptor *CmdID_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL CmdID_IsValidValue(int32_t value);

#pragma mark - MessagecmdRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface MessagecmdRoot : GPBRootObject
@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
