// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: c2kf.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers_RuntimeSupport.h>
#else
 #import "GPBProtocolBuffers_RuntimeSupport.h"
#endif

 #import "C2Kf.pbobjc.h"
// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

#pragma mark - C2KfRoot

@implementation C2KfRoot

// No extensions in the file and no imports, so no need to generate
// +extensionRegistry.

@end

#pragma mark - C2KfRoot_FileDescriptor

static GPBFileDescriptor *C2KfRoot_FileDescriptor(void) {
  // This is called by +initialize so there is no need to worry
  // about thread safety of the singleton.
  static GPBFileDescriptor *descriptor = NULL;
  if (!descriptor) {
    GPB_DEBUG_CHECK_RUNTIME_VERSIONS();
    descriptor = [[GPBFileDescriptor alloc] initWithPackage:@"protocol.protobuf"
                                                     syntax:GPBFileSyntaxProto3];
  }
  return descriptor;
}

#pragma mark - C2KfRequest

@implementation C2KfRequest

@dynamic from;
@dynamic fromName;
@dynamic fromDomain;
@dynamic guid;
@dynamic chatId;
@dynamic sceneId;
@dynamic content;
@dynamic type;
@dynamic appId;
@dynamic ext;

typedef struct C2KfRequest__storage_ {
  uint32_t _has_storage_[1];
  int32_t fromDomain;
  int32_t type;
  NSString *from;
  NSString *fromName;
  NSString *guid;
  NSString *sceneId;
  NSString *content;
  NSString *appId;
  NSString *ext;
  int64_t chatId;
} C2KfRequest__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "from",
        .dataTypeSpecific.className = NULL,
        .number = C2KfRequest_FieldNumber_From,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(C2KfRequest__storage_, from),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "fromName",
        .dataTypeSpecific.className = NULL,
        .number = C2KfRequest_FieldNumber_FromName,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(C2KfRequest__storage_, fromName),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "fromDomain",
        .dataTypeSpecific.className = NULL,
        .number = C2KfRequest_FieldNumber_FromDomain,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(C2KfRequest__storage_, fromDomain),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeInt32,
      },
      {
        .name = "guid",
        .dataTypeSpecific.className = NULL,
        .number = C2KfRequest_FieldNumber_Guid,
        .hasIndex = 3,
        .offset = (uint32_t)offsetof(C2KfRequest__storage_, guid),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "chatId",
        .dataTypeSpecific.className = NULL,
        .number = C2KfRequest_FieldNumber_ChatId,
        .hasIndex = 4,
        .offset = (uint32_t)offsetof(C2KfRequest__storage_, chatId),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeInt64,
      },
      {
        .name = "sceneId",
        .dataTypeSpecific.className = NULL,
        .number = C2KfRequest_FieldNumber_SceneId,
        .hasIndex = 5,
        .offset = (uint32_t)offsetof(C2KfRequest__storage_, sceneId),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "content",
        .dataTypeSpecific.className = NULL,
        .number = C2KfRequest_FieldNumber_Content,
        .hasIndex = 6,
        .offset = (uint32_t)offsetof(C2KfRequest__storage_, content),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "type",
        .dataTypeSpecific.className = NULL,
        .number = C2KfRequest_FieldNumber_Type,
        .hasIndex = 7,
        .offset = (uint32_t)offsetof(C2KfRequest__storage_, type),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeInt32,
      },
      {
        .name = "appId",
        .dataTypeSpecific.className = NULL,
        .number = C2KfRequest_FieldNumber_AppId,
        .hasIndex = 8,
        .offset = (uint32_t)offsetof(C2KfRequest__storage_, appId),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "ext",
        .dataTypeSpecific.className = NULL,
        .number = C2KfRequest_FieldNumber_Ext,
        .hasIndex = 9,
        .offset = (uint32_t)offsetof(C2KfRequest__storage_, ext),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[C2KfRequest class]
                                     rootClass:[C2KfRoot class]
                                          file:C2KfRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(C2KfRequest__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
#if !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    static const char *extraTextFormatInfo =
        "\005\002\010\000\003\n\000\005\006\000\006\007\000\t\005\000";
    [localDescriptor setupExtraTextInfo:extraTextFormatInfo];
#endif  // !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - C2KfResponse

@implementation C2KfResponse

@dynamic msgid;
@dynamic timestamp;

typedef struct C2KfResponse__storage_ {
  uint32_t _has_storage_[1];
  int64_t msgid;
  int64_t timestamp;
} C2KfResponse__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "msgid",
        .dataTypeSpecific.className = NULL,
        .number = C2KfResponse_FieldNumber_Msgid,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(C2KfResponse__storage_, msgid),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeInt64,
      },
      {
        .name = "timestamp",
        .dataTypeSpecific.className = NULL,
        .number = C2KfResponse_FieldNumber_Timestamp,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(C2KfResponse__storage_, timestamp),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeInt64,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[C2KfResponse class]
                                     rootClass:[C2KfRoot class]
                                          file:C2KfRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(C2KfResponse__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end


#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
