// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: history.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class PullHistoryMsg;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - Enum PullHistoryResponse_Status

/** 状态枚举 */
typedef GPB_ENUM(PullHistoryResponse_Status) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  PullHistoryResponse_Status_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  PullHistoryResponse_Status_Ok = 0,
  PullHistoryResponse_Status_Err = 1,
};

GPBEnumDescriptor *PullHistoryResponse_Status_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL PullHistoryResponse_Status_IsValidValue(int32_t value);

#pragma mark - HistoryRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface HistoryRoot : GPBRootObject
@end

#pragma mark - PullHistoryRequest

typedef GPB_ENUM(PullHistoryRequest_FieldNumber) {
  PullHistoryRequest_FieldNumber_Uid = 1,
  PullHistoryRequest_FieldNumber_Domain = 2,
  PullHistoryRequest_FieldNumber_ChatId = 3,
  PullHistoryRequest_FieldNumber_AppId = 4,
  PullHistoryRequest_FieldNumber_SceneId = 5,
  PullHistoryRequest_FieldNumber_ClientType = 6,
  PullHistoryRequest_FieldNumber_Offset = 7,
  PullHistoryRequest_FieldNumber_Limit = 8,
  PullHistoryRequest_FieldNumber_LogId = 9,
};

@interface PullHistoryRequest : GPBMessage

/** 用户id,包含内部、外部、匿名 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *uid;

/** 用户所属类别，见枚举类UserDomain */
@property(nonatomic, readwrite) int32_t domain;

/** 会话ID */
@property(nonatomic, readwrite) int64_t chatId;

/** app标识，如瓜子，毛豆app */
@property(nonatomic, readwrite, copy, null_resettable) NSString *appId;

/** 场景ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *sceneId;

/** IM端类型，见枚举类ClientType, 未来用来过滤这个端发出来的消息 */
@property(nonatomic, readwrite) int32_t clientType;

/** 拉取消息起始位置，初始是0，之后用服务器返回的数据 */
@property(nonatomic, readwrite) int64_t offset;

/** 单次拉取消息的数量，默认值50 */
@property(nonatomic, readwrite) int32_t limit;

/** 服务端traceid，用于跟踪消息流转全链路 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *logId;

@end

#pragma mark - PullHistoryMsg

typedef GPB_ENUM(PullHistoryMsg_FieldNumber) {
  PullHistoryMsg_FieldNumber_From = 1,
  PullHistoryMsg_FieldNumber_FromName = 2,
  PullHistoryMsg_FieldNumber_FromDomain = 3,
  PullHistoryMsg_FieldNumber_ChatId = 4,
  PullHistoryMsg_FieldNumber_Content = 5,
  PullHistoryMsg_FieldNumber_Msgid = 6,
  PullHistoryMsg_FieldNumber_Sequence = 7,
  PullHistoryMsg_FieldNumber_CmdId = 8,
  PullHistoryMsg_FieldNumber_SendTime = 9,
  PullHistoryMsg_FieldNumber_Type = 10,
  PullHistoryMsg_FieldNumber_AppId = 11,
  PullHistoryMsg_FieldNumber_SceneId = 12,
  PullHistoryMsg_FieldNumber_Extra = 13,
};

@interface PullHistoryMsg : GPBMessage

/** 发送者id */
@property(nonatomic, readwrite, copy, null_resettable) NSString *from;

@property(nonatomic, readwrite, copy, null_resettable) NSString *fromName;

/** 发送者所属用户类型,具体见DomainType */
@property(nonatomic, readwrite) int32_t fromDomain;

/** 会话ID */
@property(nonatomic, readwrite) int64_t chatId;

/** 消息内容 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *content;

/** 消息服务器对消息的编号， */
@property(nonatomic, readwrite) int64_t msgid;

/** 按人全局唯一的消息序号 */
@property(nonatomic, readwrite) int32_t sequence;

/** 消息原始命令号，可标识消息类型 */
@property(nonatomic, readwrite) int32_t cmdId;

/** 服务器接收消息时间 */
@property(nonatomic, readwrite) int64_t sendTime;

/** 消息内容类型，比如文本，图片，文件等 */
@property(nonatomic, readwrite) int32_t type;

/** app标识，如瓜子，毛豆app */
@property(nonatomic, readwrite, copy, null_resettable) NSString *appId;

/** 场景ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *sceneId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *extra;

@end

#pragma mark - PullHistoryResponse

typedef GPB_ENUM(PullHistoryResponse_FieldNumber) {
  PullHistoryResponse_FieldNumber_MsgArray = 1,
  PullHistoryResponse_FieldNumber_Status = 2,
};

@interface PullHistoryResponse : GPBMessage

/** 消息，采用富文本传输 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<PullHistoryMsg*> *msgArray;
/** The number of items in @c msgArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger msgArray_Count;

/** 状态，使用枚举 */
@property(nonatomic, readwrite) int32_t status;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
