// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: notify.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

NS_ASSUME_NONNULL_BEGIN

#pragma mark - NotifyRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface NotifyRoot : GPBRootObject
@end

#pragma mark - NotifyRequest

typedef GPB_ENUM(NotifyRequest_FieldNumber) {
  NotifyRequest_FieldNumber_Msgid = 1,
  NotifyRequest_FieldNumber_LogId = 2,
  NotifyRequest_FieldNumber_Sequence = 3,
};

@interface NotifyRequest : GPBMessage

/** 消息服务器对消息的编号 */
@property(nonatomic, readwrite) int64_t msgid;

/** 服务端traceid，用于跟踪消息流转全链路。 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *logId;

/** 按人全局唯一的消息序号 */
@property(nonatomic, readwrite) int32_t sequence;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
