// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sysmsg.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

NS_ASSUME_NONNULL_BEGIN

#pragma mark - Enum SysMsgPushRequest_SysMsgType

typedef GPB_ENUM(SysMsgPushRequest_SysMsgType) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  SysMsgPushRequest_SysMsgType_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  /** C端用户关注的系统消息 */
  SysMsgPushRequest_SysMsgType_Welcome = 0,

  /** 客服接入 */
  SysMsgPushRequest_SysMsgType_KfAcceptRequest = 1,

  /** 排队 */
  SysMsgPushRequest_SysMsgType_WaitForKf = 2,

  /** 客服离线 */
  SysMsgPushRequest_SysMsgType_KfOffline = 3,

  /** 客服转其他客服 */
  SysMsgPushRequest_SysMsgType_KfTurnOtherKf = 4,

  /** /用户与客服结束会话，客服发起 */
  SysMsgPushRequest_SysMsgType_EndConversationWithKf = 5,
};

GPBEnumDescriptor *SysMsgPushRequest_SysMsgType_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL SysMsgPushRequest_SysMsgType_IsValidValue(int32_t value);

#pragma mark - SysmsgRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface SysmsgRoot : GPBRootObject
@end

#pragma mark - SysMsgPushRequest

typedef GPB_ENUM(SysMsgPushRequest_FieldNumber) {
  SysMsgPushRequest_FieldNumber_From = 1,
  SysMsgPushRequest_FieldNumber_FromDomain = 2,
  SysMsgPushRequest_FieldNumber_FromName = 3,
  SysMsgPushRequest_FieldNumber_To = 4,
  SysMsgPushRequest_FieldNumber_ToDomain = 5,
  SysMsgPushRequest_FieldNumber_Type = 6,
  SysMsgPushRequest_FieldNumber_Msgid = 7,
  SysMsgPushRequest_FieldNumber_Content = 8,
  SysMsgPushRequest_FieldNumber_ChatId = 9,
  SysMsgPushRequest_FieldNumber_SceneId = 10,
  SysMsgPushRequest_FieldNumber_AppId = 11,
};

@interface SysMsgPushRequest : GPBMessage

/** 发送者 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *from;

/** 发送者域 */
@property(nonatomic, readwrite) int32_t fromDomain;

@property(nonatomic, readwrite, copy, null_resettable) NSString *fromName;

/** 接收者 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *to;

/** 接收者域 */
@property(nonatomic, readwrite) int32_t toDomain;

/** 系统消息类型,SysMsgType */
@property(nonatomic, readwrite) int32_t type;

/** 消息服务器对消息的编号(针对每个用户独立的一份消息) */
@property(nonatomic, readwrite) int64_t msgid;

/** 消息内容 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *content;

/** 会话ID */
@property(nonatomic, readwrite) int64_t chatId;

/** 场景ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *sceneId;

/** app标识，如瓜子，毛豆app */
@property(nonatomic, readwrite, copy, null_resettable) NSString *appId;

@end

#pragma mark - SysMsgPushResponse

typedef GPB_ENUM(SysMsgPushResponse_FieldNumber) {
  SysMsgPushResponse_FieldNumber_Msgid = 1,
  SysMsgPushResponse_FieldNumber_Timestamp = 2,
};

@interface SysMsgPushResponse : GPBMessage

/** 落地存储的消息id */
@property(nonatomic, readwrite) int64_t msgid;

/** 收到单聊消息的时间戳 */
@property(nonatomic, readwrite) int64_t timestamp;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
